using System;
using Content.Client.Links;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.IoC;

namespace Content.Client.Info;

[GenerateTypedNameReferences]
public sealed partial class RulesLinksSection : BoxContainer
{
    public RulesLinksSection()
    {
        RobustXamlLoader.Load(this);

        var uriOpener = IoCManager.Resolve<IUriOpener>();

        DiscordButton.OnPressed += args => uriOpener.OpenUri(UILinks.Discord);
        RolesButton.OnPressed += args => uriOpener.OpenUri(UILinks.Roles);
        LawsButton.OnPressed += args => uriOpener.OpenUri(UILinks.Laws);
    }
}
