name: Changelogs

concurrency:
  group: changelogs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches: [ arumoon-server ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Publish changelog
      run: Tools/actions_changelogs_since_last_run.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK }}
